### ISSUE TITLE
[PARTY] The Examples Never Load

### ISSUE THREAD

**Issue by carlsmith** [sjfricke/awesome-webgl#13]
When visiting `regl.party/examples`,  none of the examples load. The page says *loading...*, but it never changes. There are no errors reported in the console. It's a shame, as the library still looks interesting.

Chrome 71
MacOS 10.14.2

**Comment by sjfricke** [comment]
Agree it is a shame, but there is already an issue reported in the regl repo
https://github.com/regl-project/regl/issues/519
https://github.com/regl-project/regl/issues/521
